### PR TITLE
Create bg.json

### PR DESCRIPTION
**Pull request by AlexanderTonev**
Translation in Bulgarian

### CODE REVIEW

**Comment by brunto** [comment]
Thanks, @AlexanderTonev for this translation. We'll review it soon.

**Comment by brunto** [comment]
Sorry @AlexanderTonev for the delay. We'll integrate it in the next release 3.0

**Comment by kosmas58** [comment]
I've integrated bulgarian into [my prerelease of 3.0](https://github.com/kosmas58/pia/tree/pia-3-04-b-risk3Letter) . You can test it there. Necessary steps to test it are:

1.  Install node.js
2.  Install yarn
3.  run `yarn`
4.  run `yarn start`
5. call `http://localhost:4200` in your browser

**Comment by brunto** [comment]
@kosmas58 @AlexanderTonev 
You have now a new repository for the next version (3.0) of PIA for all locales.
See: https://github.com/LINCnil/pia-i18n 
This repository centralizes all JSON for each lang.
@AlexanderTonev Do you have the time to move this PR inside this new repository?

**Comment by AlexanderTonev** [comment]
Dear Bruno,
I hope I managed to transfer the repository by importing it to the location below
Regards,
Aleks Tonev

________________________________
От: Bruno Perles ***@***.***>
Изпратено: 28 април 2021 г. 22:15
До: LINCnil/pia ***@***.***>
Як: Alexander Tonev ***@***.***>; Mention ***@***.***>
Тема: Re: [LINCnil/pia] Create bg.json (#498)


@kosmas58<https://github.com/kosmas58> @AlexanderTonev<https://github.com/AlexanderTonev>
You have now a new repository for the next version (3.0) of PIA for all locales.
See: https://github.com/LINCnil/pia-i18n
This repository centralizes all JSON for each lang.
@AlexanderTonev<https://github.com/AlexanderTonev> Do you have the time to move this PR inside this new repository?

**Comment by brunto** [comment]
@syl-p @kevin-atnos We need to import this locale inside https://github.com/LINCnil/pia-i18n

**Pull request closed without merging**
