### PR TITLE
Create dk.json

### PR DESCRIPTION
**Pull request by moolsen**
I have translated en.json to Danish, I also used the original fr.json source for some of the translations.
I guess that someone needs to look at my suggested file, there are some red markups that I do not know how to handle. 

NB: This is my very first contribution through Github, so very newbie.

Thanks for helping out
Michael

### CODE REVIEW

**Comment by DimitrisTzellis** [comment]
Welcome to the community!

      "cz": "Tjekkisk",
      "de": "Tysk",
are consistently translated into each respective language, so that the end user sees:
      "cz": "Česky",
      "de": "Deutsch",
etc.

in PIA_SEC_CTR the "source": "Digitaliseringsstyrelsen; Sådan stiller du krav til leverandører om informationssikkerhed <a target=\"_blank\"href=\https://digst.dk/... 
should be 
<a target=\"_blank\" href=\"https://digst.dk/... 
in order to "escape the character"

Great work. Keep it up.

**Comment by moolsen** [comment]
Dear contributors,  is something else required from my side for the translation?
kind regards Michael

**Comment by kosmas58** [comment]
My RubyMine editor found two errors in dk.json, which I've corrected. I've created a pull request for you.

@LaboCNIL generally needs some time to pull the requests. In [my development version](https://github.com/kosmas58/pia/tree/develop) dansk is already integrated.

Kind regards Kosmas

**Comment by moolsen** [comment]
Dear community, what is required for a review and who is eligible for doing it?

Thanks - Michael (-:

**Comment by moolsen** [comment]
Bonjour,


the added text for v2 has been translated in dk.json.




Cordialement


Michael




med venlig hilsen


Michael Drews Olsen







On Mon, Oct 29, 2018 at 2:08 PM +0100, "LINC" <notifications@github.com> wrote:












@LaboCNIL requested changes on this pull request.



Hi @moolsen ,

Thank you for your awesome translation! We've updated your file with some new fields so that it is ready for the 2.0 release. Would you have the time to translate those new elements this week?


Best regards,

LaboCNIL

**Comment by LaboCNIL** [comment]
Hi @moolsen 
Thanks for translating the remaining fields! The translation will be available in the next release of the tool.

Best regards,
LaboCNIL

**Pull request merged**
