### PR TITLE
Create es.json

### PR DESCRIPTION
**Pull request by ylachgar**
Hi All,

I just finish the translation in spanish, i would like to have it merge asap could be useful for few users :)

### CODE REVIEW

**Comment by kosmas58** [comment]
After fixing several typos in your es.json, I've included your translation in my pull request #66.

**Comment by ylachgar** [comment]
Thanks @kosmas58

**Comment by kosmas58** [comment]
You're welcome. My RubyMine editor found the bugs, so it wasn't much work. In _translators_name_ I used your GitHub name. I've you want to be shown with your full name like the others and me, let me know.

**Comment by LaboCNIL** [comment]
As @kosmas58 has commited this translation through #78 request, we close this one.
Thanks for your contribution!

**Pull request closed without merging**
