### PR TITLE
Create hr.json

### PR DESCRIPTION
**Pull request by B2KapitalBA**
This is the PIA translation to Croatian, done by certified and official translator.

### CODE REVIEW

**Comment by B2KapitalBA** [comment]
Please assign someone to review this so we can merge it to master and start using it.

**Comment by B2KapitalBA** [comment]
Dear LaboCNIL,

when can we expect a review of this file?

Kind regards,
Goran V.

**Comment by LaboCNIL** [comment]
Hi Goran,
Thanks a lot for the translation! We've just checked the file and we've added the fields required in 2.0. Would you have the time to translate those new fields? 

Best regards,
LaboCnil

**Comment by B2KapitalBA** [comment]
Dear LaboCNIL,

we have delivered the requested changes and we kindly ask for a new review.

Kind regards,
Goran V.

**Comment by LaboCNIL** [comment]
Hi @B2KapitalBA 
Thanks a lot for your effort. It is now merged and will be available in the next release of the tool.

Best regards,
Labo CNIL

**Comment by B2KapitalBA** [comment]
Dear LaboCNIL,

when is the next release planned for?

Kind regards,
Goran V.

**Comment by LaboCNIL** [comment]
It should happen next week or the week after.

**Comment by B2KapitalBA** [comment]
Dear LaboCNIL,

any news on next release?

Kind regards,
Goran V.

**Pull request merged**
