### PR TITLE
Create lt.json

### PR DESCRIPTION
**Pull request by i4paga**
This is Lithuanian translation of PIA software provided by Law firm Galubickas www.galubickas.lt

### CODE REVIEW

**Comment by i4paga** [comment]
Lithuanian translation is finished, please include it into new release

**Comment by kevin-atnos** [comment]
Hello,

We are working on releasing the final version of the PIA tool very soon.

We will then study all contributions from the community and try to include the most adequate ones.
Your translation will probably be included too as it is missing now.

Thank you for your comprehension.

**Comment by i4paga** [comment]
It would be great if you include my Lithuanian translation into new release. Many Lithuanians companies and DPOs are keen to start using your software for PIA in native language.

Paulius Galubickas, Advokatas/Attorney
+37061613406, paulius@galubickas.lt<mailto:paulius@galubickas.lt>
www.galubickas.lt<http://www.galubickas.lt/>

**Comment by i4paga** [comment]
Hi, I have updated Lithuanian translation accordingly.

Regards

Paulius Galubickas, Advokatas/Attorney
+37061613406, paulius@galubickas.lt<mailto:paulius@galubickas.lt>
www.galubickas.lt<http://www.galubickas.lt/>

**Comment by LaboCNIL** [comment]
Hi,
Thank you so much for the changes! The translation will be available in the next version of the tool.

Best regards,
LaboCNIL

**Comment by i4paga** [comment]
Is it not too late, to make few grammar corrections in Lithuanian translation?

Paulius Galubickas, Advokatas/Attorney
+37061613406, paulius@galubickas.lt<mailto:paulius@galubickas.lt>
www.galubickas.lt<http://www.galubickas.lt/>

**Pull request merged**
